### ISSUE TITLE
Status is not updating

### ISSUE THREAD

**Issue by fokcuk** [DeebotUniverse/docs#219]
As of late (last week) Deebot status has not been updating.
Manual update through services works, but I wonder if its to do with any of the HA updates
The following error is logged:

```
This error originated from a custom integration.

Logger: custom_components.deebot.hub
Source: custom_components/deebot/hub.py:114
Integration: Deebot 4 Home Assistant (documentation, issues)
First occurred: 2:58:25 AM (2 occurrences)
Last logged: 12:10:03 PM

failure (3002) on getting devices
Traceback (most recent call last):
  File "/config/custom_components/deebot/hub.py", line 104, in _check_status_task
    await self._check_status_function()
  File "/config/custom_components/deebot/hub.py", line 114, in _check_status_function
    devices = await self._api_client.get_devices()
  File "/usr/local/lib/python3.10/site-packages/deebot_client/api_client.py", line 61, in get_devices
    raise ApiError(
deebot_client.exceptions.ApiError: failure  (3002) on getting devices
```

**Comment by fokcuk** [comment]
can be closed - updated HA and it seems to be ok now
